name: Node.js tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack-s3:
        image: localstack/localstack
        env:
          HOSTNAME: localhost
          SERVICES: s3:5000
          DEFAULT_REGION: eu-west-1
        ports:
          - '5000:5000'
          - '8080:8080'
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: |
          yarn test:local
          yarn lint
        env:
          GITHUB_ACTION: true
          GCS_KEY: ${{secrets.GCS_KEY}}
          S3_KEY: no_need
          S3_SECRET: no_need
          S3_ENDPOINT: http://localhost:5000
          S3_BUCKET: testbucket
          S3_REGION: eu-west-1
